"""Job-specific AI learning plan model.

One plan per (user, job). Generated by AI from skill gap analysis.
Progress is tracked per resource item inside the JSONB plan.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


def _uuid():
    return uuid.uuid4()


def _now():
    return datetime.now(timezone.utc)


class JobLearningPlan(Base):
    """AI-generated, job-specific learning roadmap for a user.

    plan JSONB structure:
    {
      "job_title": str,
      "company": str,
      "summary": str,                    # one-line "why this plan"
      "total_estimated_hours": int,
      "modules": [
        {
          "id": str,                     # stable slug e.g. "mod-1"
          "skill": str,
          "priority": int,               # 1 = highest
          "why_important": str,          # specific to this job
          "estimated_hours": int,
          "resources": [
            {
              "id": str,                 # e.g. "mod-1-res-1"
              "type": "youtube"|"article"|"course",
              "title": str,
              "channel_or_source": str,
              "search_query": str,       # for constructing YT search URL
              "url": str,                # YouTube search URL or direct link
              "duration_minutes": int,
              "description": str
            }
          ]
        }
      ]
    }

    progress JSONB structure:
    { "<resource_id>": { "done": bool, "done_at": iso_str | null } }
    """
    __tablename__ = "job_learning_plans"

    id          = Column(UUID(as_uuid=True), primary_key=True, default=_uuid)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    job_id      = Column(UUID(as_uuid=True), ForeignKey("job_postings.id", ondelete="CASCADE"), nullable=False, index=True)
    plan        = Column(JSONB, nullable=False, server_default="{}")
    progress    = Column(JSONB, nullable=False, server_default="{}")
    status      = Column(String(20), nullable=False, default="generating")  # generating | ready | failed
    error_msg   = Column(Text, nullable=True)
    generated_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at  = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    user = relationship("User", foreign_keys=[user_id])
    job  = relationship("JobPosting", foreign_keys=[job_id])
